tests: Fix whitespace issues with tests/cthon04/*.patch patches
Fix whitespace issues with tests/cthon04/*.patch patches, somehow
the whiitespaces got mangled to death, and could no longer be applied:
---- snip ----
git clone https://github.com/kofemann/ms-nfs41-client.git
git clone git://git.linux-nfs.org/projects/steved/cthon04.git
cd cthon04/
git config --global --add safe.directory "$PWD"
git checkout 6c9abfd6907b2b43036af111cc600ab60ef804e5
git am ../ms-nfs41-client/tests/cthon04/*.patch
Cloning into 'ms-nfs41-client'...
remote: Enumerating objects: 8594, done.
remote: Counting objects: 100% (615/615), done.
remote: Compressing objects: 100% (348/348), done.
remote: Total 8594 (delta 408), reused 408 (delta 258), pack-reused
7979 (from 2)
Receiving objects: 100% (8594/8594), 3.35 MiB | 549.00 KiB/s, done.
Resolving deltas: 100% (6379/6379), done.
Cloning into 'cthon04'...
remote: Counting objects: 363, done.
remote: Compressing objects: 100% (162/162), done.
remote: Total 363 (delta 233), reused 303 (delta 200)
Receiving objects: 100% (363/363), 143.39 KiB | 169.00 KiB/s, done.
Resolving deltas: 100% (233/233), done.
Note: switching to '6c9abfd6907b2b43036af111cc600ab60ef804e5'.
HEAD is now at 6c9abfd Cleaned up more warnings
Applying: tools: Cygwin 3.6 port
error: corrupt patch at line 21
Patch failed at 0001 tools: Cygwin 3.6 port
hint: Use 'git am --show-current-patch=diff' to see the failed patch
When you have resolved this problem, run "git am --continue".
If you prefer to skip this patch, run "git am --skip" instead.
To restore the original branch and stop patching, run "git am --abort".
---- snip ----

Reported-by: Sebastian Feld <sebastian.n.feld@gmail.com>
Signed-off-by: Cedric Blancher <cedric.blancher@gmail.com>
Signed-off-by: Tigran Mkrtchyan <tigran.mkrtchyan@desy.de>